@protocol WebCaretChangeListener
- (void)caretChanged;
@end

@interface UIAutocorrectInlinePrompt : UIView
{
    struct CGRect m_originalTypedTextRect;
    NSString *m_typedText;
    NSString *m_correction;
    UIView *m_typedTextView;
    UIView *m_correctionView;
    UIView *m_correctionAnimationView;
    UIView *m_typedTextAnimationView;
    UIView *m_correctionShadowView;
    int m_position;
    BOOL m_fits;
    BOOL m_mouseDown;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)dealloc;
- (void)removePromptSubviews;
- (struct CGRect)shadowFrameForFrame:(struct CGRect)fp8;
- (void)setCorrection:(id)fp8 typedText:(id)fp12 inRect:(struct CGRect)fp16 maxX:(float)fp32;
- (id)correction;
- (void)setPosition:(int)fp8;
- (int)position;
- (id)typedTextView;
- (id)correctionView;
- (id)correctionAnimationView;
- (id)typedTextAnimationView;
- (id)correctionShadowView;
- (BOOL)pointInside:(struct CGPoint)fp8 forEvent:(struct __GSEvent *)fp16;
- (void)dismiss;
- (void)mouseDown:(struct __GSEvent *)fp8;
- (void)mouseDragged:(struct __GSEvent *)fp8;
- (void)mouseUp:(struct __GSEvent *)fp8;
- (BOOL)prepareForAnimation:(struct CGRect)fp8;
- (struct CGRect)topRect;
- (struct CGRect)bottomRect;

@end

@interface UIKBInputManager : NSObject
{
}

+ (void)registerCentroid:(struct CGPoint)fp8 forKey:(id)fp16;
+ (void)clearCentroids;
+ (void)removeAllDynamicDictionaries;
+ (id)sharedInstance;
+ (id)activeInstance;
+ (void)releaseSharedInstance;
- (id)init;
- (void)dealloc;
- (void)setAutocorrectStemsForCurrentLanguage;
- (void)languageChanged;
- (int)textDomain;
- (void)setTextDomain:(int)fp8;
- (int)lookupMode;
- (void)setLookupMode:(int)fp8;
- (void)setAutoCorrecting:(BOOL)fp8;
- (void)setCalculatesNextCharacterProbabilities:(BOOL)fp8;
- (void)setTestMode;
- (void)clearDynamicDictionary;
- (void)addInput:(id)fp8 flags:(unsigned int)fp12 point:(struct CGPoint)fp16;
- (void)setInput:(id)fp8;
- (void)deleteFromInput;
- (void)clearInput;
- (void)acceptInput;
- (void)clearMarkedInput;
- (void)acceptMarkedInput;
- (void)setInputIndex:(unsigned int)fp8;
- (unsigned int)inputIndex;
- (int)inputCount;
- (id)inputString;
- (void)noteUserTypedWord:(id)fp8 weight:(int)fp12;
- (void)noteUserDeletedWord;
- (void)noteUserDeletedWord:(id)fp8;
- (void)selectionChanged;
- (void)clearTypingHistory;
- (id)shadowTyping;
- (void)setShift:(BOOL)fp8;
- (void)setAutoShiftFlag:(BOOL)fp8;
- (void)nextCharacterProbabilities:(float **)fp8;
- (id)autocorrection;
- (id)generateSuggestions;
- (id)generateSuggestions:(BOOL)fp8;

@end

@interface UIKeyboardLanguageIndicator : UIView
{
    int m_language;
    UIImage *m_image;
    float m_textSize;
    int m_style;
}

- (id)initWithFrame:(struct CGRect)fp8;
- (void)setBackgroundImage:(id)fp8;
- (void)setTextSize:(float)fp8;
- (void)setStyle:(int)fp8;
- (void)fade;
- (void)fadeAnimationDidStop:(id)fp8 finished:(id)fp12;
- (void)drawRect:(struct CGRect)fp8;

@end


@interface UIKeyboardImpl : UIView <WebCaretChangeListener>
{
    id <UIKeyboardInput> m_delegate;
    UITextTraits *m_defaultTextTraits;
    NSString *m_preferenceName;
    int m_userInterfaceLanguage;
    UIKeyboardLanguageIndicator *m_languageIndicator;
    NSArray *m_suggestions;
    NSString *m_autocorrection;
    NSString *m_previousInputString;
    UIKBInputManager *m_inputManager;
    UIAutocorrectInlinePrompt *m_autocorrectPrompt;
    unsigned int m_markedTextLength;
    NSString *m_acceptedText;
    NSMutableDictionary *m_autocorrectionHistory;
    NSMutableDictionary *m_keyedLayouts;
    UIView *m_layout;
    Class m_preferredLayoutClass;
    NSTimer *m_autoDeleteTimer;
    unsigned int m_autoDeleteCount;
    unsigned short m_autoDeleteShiftCharacter;
    UIDelayedAction *m_longPressAction;
    int m_orientation;
    UIView *m_caretView;
    NSTimer *m_caretTimer;
    struct CGPoint m_keyPoint;
    int m_changeCount;
    double m_changeTime;
    struct __CFRunLoopObserver *m_observer;
    struct CGColor *m_caretColor;
    struct __CFCharacterSet *m_textTrimmingSet;
    id m_editingDelegate;
    id m_textSuggestionDelegate;
    int m_autoCapsType;
    int m_autoCorrectionType;
    int m_initialSelectionBehavior;
    unsigned int m_caretWidth;
    int m_preferredKeyboardType;
    int m_returnKeyType;
    int m_textDomain;
    int m_textLoupeVisibility;
    BOOL m_autoEnablesReturnKey;
    BOOL m_secureTextEntry;
    BOOL m_singleCompletionEntry;
    BOOL m_autoCapitalizationPreference;
    BOOL m_autoCorrectionPreference;
    BOOL m_doubleSpacePeriodPreference;
    BOOL m_autoCorrect;
    BOOL m_autoDeleteOK;
    BOOL m_autoShifted;
    BOOL m_initializationDone;
    BOOL m_defaultsNeedSynchronization;
    BOOL m_shift;
    BOOL m_shiftLockedEnabled;
    BOOL m_shiftLocked;
    BOOL m_soundsEnabled;
    BOOL m_changed;
    BOOL m_selecting;
    BOOL m_returnKeyEnabled;
    BOOL m_caretVisible;
    BOOL m_caretBlinks;
    BOOL m_caretShowingNow;
    BOOL m_userChangedSelection;
    BOOL m_shouldChargeKeys;
    BOOL m_longPress;
}

+ (id)sharedInstance;
+ (id)activeInstance;
+ (void)releaseSharedInstance;
+ (struct CGSize)defaultSize;
+ (struct CGSize)suggestionBarSize;
+ (struct CGSize)defaultSizeForOrientation:(int)fp8;
+ (struct CGSize)suggestionBarSizeForOrientation:(int)fp8;
+ (struct CGSize)keypadSize;
+ (struct CGSize)keypadSizeForOrientation:(int)fp8;
+ (void)removeAllDynamicDictionaries;
+ (int)orientationForSize:(struct CGSize)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)delayedInitialization;
- (void)dealloc;
- (void)clearLayouts;
- (void)removeFromSuperview;
- (void)applicationSuspendedEventsOnly:(id)fp8;
- (void)applicationResumedEventsOnly:(id)fp8;
- (void)defaultsDidChange;
- (void)defaultsDidChange:(id)fp8;
- (id)synchronizedUserDefaults;
- (BOOL)autoCapitalizationPreference;
- (BOOL)doubleSpacePeriodPreference;
- (BOOL)autoCorrectionPreference;
- (void)setAutoCorrectionPreference:(BOOL)fp8;
- (void)setAutoCorrect:(BOOL)fp8;
- (BOOL)autoCorrect;
- (int)languagePreference;
- (id)keyboardsPreference;
- (int)keyboardLastUsedPreference;
- (void)setKeyboardLastUsedPreference;
- (BOOL)shiftLockPreference;
- (void)setTestMode;
- (void)clearDynamicDictionary;
- (int)language;
- (void)setLanguage:(int)fp8;
- (void)setLanguageFromPreferences;
- (void)setLanguageToNextInPreferredList;
- (void)setOrientationForSize:(struct CGSize)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)takeTraitsFrom:(id)fp8;
- (id)delegate;
- (void)setDelegate:(id)fp8;
- (void)setDelegate:(id)fp8 force:(BOOL)fp12;
- (void)textChanged:(id)fp8;
- (void)setDefaultTextTraits:(id)fp8;
- (int)preferredKeyboardType;
- (void)setPreferredKeyboardType:(int)fp8;
- (id)layoutKeyForPreferredKeyboardType;
- (void)showPreferredKeyboardType;
- (void)enable;
- (BOOL)callShouldInsertText:(id)fp8 isMarkedText:(BOOL)fp12;
- (BOOL)callShouldDelete;
- (void)callChangedSelection;
- (id)callInputOverlayContainer;
- (int)callPositionForAutocorrection:(id)fp8;
- (void)callChanged;
- (void)setChanged;
- (void)clearChangedDelegate;
- (void)prepareForGeometryChange;
- (void)geometryChangeDone:(BOOL)fp8;
- (void)updatePreferredLayoutClass;
- (void)updatePreferredLayoutClassFromPreferences;
- (Class)preferredLayoutClass;
- (id)preferenceName;
- (void)setPreferenceName:(id)fp8;
- (BOOL)isSuggestionBasedLayoutClass:(Class)fp8;
- (void)showPreferredLayout;
- (void)showLayout:(Class)fp8;
- (int)orientation;
- (void)notifySublayoutChanged;
- (void)notifyShiftChanged;
- (void)prepareForSelectionChange;
- (void)updateSelectionWithPoint:(struct CGPoint)fp8;
- (void)updateForChangedSelection;
- (void)updateInputManagerAutoShiftFlag;
- (void)updateShift;
- (void)setShift:(BOOL)fp8;
- (void)setShift:(BOOL)fp8 autoshift:(BOOL)fp12;
- (void)setShiftLocked;
- (BOOL)isShifted;
- (BOOL)isAutoShifted;
- (BOOL)isShiftLocked;
- (BOOL)shiftLockedEnabled;
- (void)installCaret;
- (void)clearCaret;
- (void)hideCaret:(int)fp8;
- (void)showCaret:(int)fp8;
- (void)caretBlinkTimerFired:(id)fp8;
- (void)clearCaretBlinkTimer;
- (void)touchCaretBlinkTimer;
- (void)setCaretBlinks:(BOOL)fp8;
- (void)setCaretVisible:(BOOL)fp8;
- (BOOL)caretBlinks;
- (BOOL)caretVisible;
- (void)updateCaretRect;
- (void)caretChanged;
- (void)keyActivated:(CDAnonymousStruct7 *)fp8;
- (void)keyDeactivated:(CDAnonymousStruct7 *)fp8;
- (void)setKeyPoint:(struct CGPoint)fp8;
- (BOOL)interceptKeyInput:(id)fp8;
- (BOOL)acceptInputString:(id)fp8;
- (void)setPreviousInputString:(id)fp8;
- (void)addInputString:(id)fp8;
- (void)addInputString:(id)fp8 isMarkedText:(BOOL)fp12;
- (void)acceptMarkedText;
- (void)clearMarkedText;
- (void)clearAcceptedText;
- (BOOL)acceptedTextEndsWithWhitespace;
- (BOOL)shouldEnableShiftForDeletedCharacter:(unsigned short)fp8;
- (void)handleDeleteWithZeroInputCount;
- (void)handleDeleteWithNonZeroInputCount;
- (void)deleteFromInput;
- (void)acceptSuggestion:(id)fp8;
- (void)acceptAutocorrection;
- (void)clearInput;
- (void)clearTransientState;
- (void)clearAnimations;
- (void)acceptWord:(id)fp8 addString:(id)fp12 weight:(int)fp16;
- (void)showSuggestionBar;
- (void)hideSuggestionBar;
- (id)visibleSuggestions;
- (void)setSuggestionBarTextSize:(int)fp8;
- (int)suggestionBarVisibility;
- (BOOL)suggestionBarVisible;
- (void)updateSuggestionBarVisibility:(BOOL)fp8;
- (BOOL)_shouldSuggestUserEnteredString:(id)fp8;
- (void)updateSuggestionsDisplay;
- (void)setAutocorrection:(id)fp8;
- (id)autocorrectPrompt;
- (void)removeAutocorrectPrompt;
- (int)returnKeyType;
- (BOOL)returnKeyEnabled;
- (void)setReturnKeyEnabled:(BOOL)fp8;
- (void)updateReturnKey;
- (void)updateReturnKey:(BOOL)fp8;
- (id)inputOverlayContainer;
- (struct CGRect)convertRectToAutocorrectRect:(struct CGRect)fp8 delegateView:(id)fp24 container:(id)fp28;
- (void)updateAutocorrectPrompt:(id)fp8;
- (void)animateAutocorrection;
- (void)fadeAutocorrectPrompt;
- (void)autocorrectionAnimationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (id)arrayWithInputManagerString;
- (void)setSuggestions:(id)fp8;
- (void)delegateSuggestionsForCurrentInput;
- (void)updateSuggestionsForCurrentInput;
- (id)suggestions;
- (BOOL)shouldChargeKeys;
- (void)nextCharacterProbabilities:(float **)fp8;
- (void)touchAutoDeleteTimerWithThreshold:(double)fp8;
- (void)autoDeleteTimerFired:(id)fp8;
- (void)startAutoDeleteTimer;
- (void)stopAutoDelete;
- (void)touchLongPressTimer;
- (void)clearLongPressTimer;
- (void)longPressAction;
- (BOOL)isLongPress;
- (void)clearTimers;
- (void)clearChangeTimeAndCount;
- (void)updateChangeTimeAndIncrementCount;
- (void)initializeSounds;
- (void)playKeyboardSound:(unsigned long)fp8;
- (void)setSoundsEnabled:(BOOL)fp8;
- (void)drawRect:(struct CGRect)fp8;

@end
